import { HorizontalBox, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Leaf-Chat";
    width: 1000px;
    height: 700px;

    Rectangle {
        background: #111820;

        HorizontalBox {
            // Sidebar
            VerticalBox {
                // logo
                Rectangle {
                    width: 250px;
                    height: 35px;
                    border-radius: 10px;
                    Text {
                        text: "Leaf-Chat";
                        color: #2ca400;
                        font-weight: 700;
                        font-family: "JetBrains Mono";
                        font-italic: true;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        font-size: 30px;
                    }
                }
                // chat list
                Rectangle {
                    width: 250px;

                    VerticalBox {
                        Text {
                            text: "sidebar";
                            color: white;
                            font-size: 20px;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                }
            }
            
            Rectangle {
                background: #0d3a0e;

                Text {
                    text: "chat area";
                    color: white;
                    font-size: 20px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
                border-radius: 10px;
                
            }
        }
    }
}