import { HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Leaf-Chat";
    width: 1000px;
    height: 700px;

    Rectangle {
        background: #111820;

        HorizontalBox {
                Rectangle {
                    width: 250px;

                    Text {
                        text: "conversations";
                        color: white;
                        font-size: 20px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            
            Rectangle {
                background: #111820;

                Text {
                    text: "chat area";
                    color: white;
                    font-size: 20px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }
        }
    }
}